Add update_field_value action
StackStorm-Exchange/jira pull request #36
Opened 2019-11-19 18:24 UTC by ytjohn

As described in #35, creates an action to update_field_value where you can set an existing field to a new value.

2019-11-19 18:27 UTC, blag requested changes

2019-11-19 18:27 UTC, blag commented on actions/update_field_value.yaml
> +
Can you remove the two extra newlines here? The file should end with only one newline.

2019-11-19 18:30 UTC, blag commented
Looks good, aside from the tiny YAML file lint issue I noted.

CI is failing, but it's not due to anything in this PR. I'll rerun the CI jobs for this PR once you fix the tiny linting thing and once https://github.com/StackStorm/st2/pull/4819 is merged.

2019-11-19 18:48 UTC, ytjohn commented
Updated with corrections.

2019-11-20 09:04 UTC, blag requested changes
Now that I got the CI jobs actually running, the flake8 linting section of the CI jobs identified two issues. I've converted them into GitHub suggestions here.

Sorry to string you along like this, but you should now have accurate feedback from the CI checks for this PR. Once you fix the remaining linting issues and CI checks all pass, I'd be happy to merge it. :smile:

2019-11-20 15:15 UTC, ytjohn commented
No problem. As the saying goes, a poor craftsman blames his tools. In this case, it was VSCode's fault as it likes to insert blank lines with spaces as a way of being "helpful". :smile:

2019-11-20 18:26 UTC, blag approved these changes
Thanks for fixing all of the linting issues!

2019-11-20 18:26 UTC, merged

2019-11-20 18:26 UTC, blag commented
Thanks for the contribution!